sonar.projectKey=wall-street-english
sonar.projectName=Wall Street English
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**
sonar.typescript.lcov.reportPaths=coverage/wall-street-english/lcov.info
sonar.sourceEncoding=UTF-8